apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: kafka
  name: kafka
spec:
  operatorVersion:
    name: kafka-0.1.0
    namespace: default
    type: OperatorVersions
  parameters:
    ZOOKEEPER_URI: "{{ .Name }}-{{ .Name }}-0.{{ .Name }}-hs:2181,{{ .Name }}-{{ .Name }}-1.{{ .Name }}-hs:2181,{{ .Name }}-{{ .Name }}-2.{{ .Name }}-hs:2181"
    ZOOKEEPER_PATH: "/kafka"
    BROKER_COUNT: "3"
    AUTO_CREATE_TOPICS_ENABLE: "true"